#!/bin/sh
#
# release/publish-javadoc -- builds and pushes the generated javadoc to the Github Pages site

set -exu

./gradlew clean
./gradlew javadoc jar

version=$(ls build/libs/rate-limited-logger-*.jar \
    | sed -e 's/^.*logger-//' -e 's/.jar//')

# Annoying javadoc bug: it'll include these annotations in the output page! remove them
sed -i '' \
    -e 's/@ParametersAreNonnullByDefault//' \
    -e 's/@DefaultAnnotation.value=javax.annotation.Nonnull.class.//' \
    build/docs/javadoc/com/swrve/ratelimitedlogger/package-summary.html

rm -rf build/gh-pages
git clone --quiet --branch=gh-pages git@github.com:Swrve/rate-limited-logger.git build/gh-pages
cd build/gh-pages

git rm -rf javadoc
mkdir javadoc
cp -R ../docs/javadoc javadoc/$version

git add -f javadoc
git commit -m "Rebuild javadoc"
git push -fq origin gh-pages

